language: python
python:
  - "2.7"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover -s tests/ # or py.test for Python versions 3.5 and below

sudo: false